---
fail_fast: true
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
          - id: check-added-large-files
            args: [--maxkb=500]
          - id: check-executables-have-shebangs
          - id: check-merge-conflict
          - id: check-toml
          - id: check-yaml
          - id: end-of-file-fixer
          - id: trailing-whitespace
    - repo: https://github.com/jumanjihouse/pre-commit-hooks
      rev: 2.1.5
      hooks:
          - id: forbid-binary
            exclude: |
                (?x)^(
                    rsc/.*\.(png|jpg|gif)
                )$
          - id: markdownlint
            exclude: |
                (?x)^(
                    docs/commands-and-functions.md
                )$
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.1.0
      hooks:
          - id: yamlfmt
    - repo: https://gitlab.com/PyCQA/flake8
      rev: 3.9.2
      hooks:
          - id: flake8
    - repo: https://github.com/PyCQA/isort
      rev: 5.9.3
      hooks:
          - id: isort
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.910
      hooks:
          - id: mypy
            args: [--ignore-missing-imports, --follow-imports=silent, --show-column-numbers, --strict, --cache-dir=/dev/null]
    - repo: https://github.com/psf/black
      rev: 21.9b0
      hooks:
          - id: black
    - repo: local
      hooks:
          - id: pytest-cov
            name: Launch tests with Pytest
            stages: [commit]
            language: system
            entry: poetry run pytest --cov --cov-fail-under=0 --cov-report term-missing
            types: [python]
            pass_filenames: false
    - repo: local
      hooks:
          - id: single-sources-of-truth
            name: Update single sources of truth
            stages: [commit]
            language: system
            entry: poetry run python single_sources.py
            pass_filenames: false
